/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @near-jsonrpc/jsonrpc-generator
 *
 * @generated
 */
/** Type alias for a method with type parameters */
export type Method<TRequest, TResponse, TError> = {
    readonly methodName: string;
};
/** Function to create a method definition with type parameters */
export declare function defineMethod<TRequest, TResponse, TError>(methodName: string): Method<TRequest, TResponse, TError>;
/** Type helper to extract the request type from a method */
export type RequestType<T extends Method<any, any, any>> = T extends Method<infer R, any, any> ? R : never;
/** Type helper to extract the response type from a method */
export type ResponseType<T extends Method<any, any, any>> = T extends Method<any, infer R, any> ? R : never;
/** Type helper to extract the error type from a method */
export type ErrorType<T extends Method<any, any, any>> = T extends Method<any, any, infer E> ? E : never;
