/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @near-jsonrpc/jsonrpc-generator
 * 
 * @generated
 */
import { z } from "zod/v4";

/** Type alias for a method with type parameters */
export type Method<TRequest, TResponse, TError, DefaultTRequest = undefined> = {
    readonly methodName: string;
    readonly zodRequest: z.ZodType<TRequest>;
    readonly zodResponse: z.ZodType<TResponse>;
    readonly zodError: z.ZodType<TError>;
    readonly defaultRequest?: DefaultTRequest;
};

/** Function to create a method definition with type parameters */
export function defineMethod<TRequest, TResponse, TError, DefaultTRequest = undefined>(methodName: string, zodRequest: z.ZodType<TRequest>, zodResponse: z.ZodType<TResponse>, zodError: z.ZodType<TError>, defaultRequest?: DefaultTRequest): Method<TRequest, TResponse, TError, DefaultTRequest> {
    return { methodName, zodRequest, zodResponse, zodError, defaultRequest };
}

/** Type helper to extract the request type from a method */
export type RequestType<T extends Method<any, any, any, any>> = T extends Method<infer R, any, any, any> ? R : never;
/** Type helper to extract the response type from a method */
export type ResponseType<T extends Method<any, any, any, any>> = T extends Method<any, infer R, any, any> ? R : never;
/** Type helper to extract the error type from a method */
export type ErrorType<T extends Method<any, any, any, any>> = T extends Method<any, any, infer E, any> ? E : never;
/** Type helper to extract the default request type from a method */
export type DefaultRequestType<T extends Method<any, any, any, any>> = T extends Method<any, any, any, infer D> ? D : never;
/** Utility type to omit properties from a type in a distributive manner */
export type DistributiveOmit<T, K extends PropertyKey> = T extends any ? Pick<T, Exclude<keyof T, K>> : never;
