import { buildTypes } from "../../src/builder/build-types";

describe("Build Types", () => {
  it("should build types text", () => {
    const fixture = {
      expect: `/**
 * THIS FILE IS GENERATED - DO NOT MODIFY DIRECTLY
 * Generated by @near-jsonrpc/jsonrpc-generator
 * 
 * @generated
 */
import { z } from "zod/v4";

/** Type alias for a method with type parameters */
export type Method<TRequest, TResponse, TError> = {
    readonly methodName: string;
    readonly zodRequest: z.ZodType<TRequest>;
    readonly zodResponse: z.ZodType<TResponse>;
    readonly zodError: z.ZodType<TError>;
};

/** Function to create a method definition with type parameters */
export function defineMethod<TRequest, TResponse, TError>(methodName: string, zodRequest: z.ZodType<TRequest>, zodResponse: z.ZodType<TResponse>, zodError: z.ZodType<TError>): Method<TRequest, TResponse, TError> {
    return { methodName, zodRequest, zodResponse, zodError };
}

/** Type helper to extract the request type from a method */
export type RequestType<T extends Method<any, any, any>> = T extends Method<infer R, any, any> ? R : never;
/** Type helper to extract the response type from a method */
export type ResponseType<T extends Method<any, any, any>> = T extends Method<any, infer R, any> ? R : never;
/** Type helper to extract the error type from a method */
export type ErrorType<T extends Method<any, any, any>> = T extends Method<any, any, infer E> ? E : never;
`,
    };
    const result = buildTypes();
    expect(result).toBe(fixture.expect);
  });
});
