name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json

      - name: Checkout repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Enable corepack
        if: ${{ steps.release.outputs.releases_created }}
        run: corepack enable

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: yarn install --frozen-lockfile

      - name: Build packages
        if: ${{ steps.release.outputs.releases_created }}
        run: yarn build

      - name: Publish jsonrpc-types
        if: ${{ steps.release.outputs['packages/jsonrpc-types--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/jsonrpc-types
          npm publish
      - name: Publish jsonrpc-client
        if: ${{ steps.release.outputs['packages/jsonrpc-client--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/jsonrpc-client
          npm publish
